<?php
namespace app\admin\controller;

use app\common\controller\AdminBase;
use think\Controller;
use app\admin\model\Menu as MenuModel;
use think\Session;

class Index extends AdminBase
{
    /**
     * 初始化后台菜单
     */
    public function initMenu()
    {
        $menu = cache("Menu");
        if (!$menu) {
            $menuModel = new MenuModel();
            $menu = $menuModel->menu_cache();
        }
        return $menu;
    }

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->initMenu();
    }

    public function index()
    {
        $menuModel = new MenuModel();
        $this->assign("SUBMENU_CONFIG", $menuModel->menu_json());
        return $this->fetch();
    }

}
